version: "3.8"

services:
  nuxt:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nuxt_engineering_blog
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
      - PORT=3000
